### ISSUE TITLE
报错：获取不到作者信息

### ISSUE THREAD

**Issue by Aprilerr** [ScottWong98/paper_spider#1]
在爬取标题为：Boosting Cross-task Transferability of Adversarial Patches with Visual Relations文章时，点开origin paper没有作者信息，导致找不到元素后报错。
![image](https://user-images.githubusercontent.com/45314441/231680388-f9bf5d34-1e74-43f6-a70c-8e3898840c4f.png)

**Comment by ScottWong98** [comment]
fix this bug in 89a3a9a9c95576b3ff431f4790e28056173d0e6a
